import Head from 'next/head'
import Image from 'next/image'
import { Shantell_Sans } from 'next/font/google'

import styles from './Welcome.module.css'

const shantell = Shantell_Sans<`--font-shantell`>({
  weight: '400',
  subsets: ['latin'],
})

export default function Welcome() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx global>{`
        html {
          font-family: ${shantell.style.fontFamily};
        }
      `}</style>
      <main className={styles.main}>
        <div className={styles.header}>
          <h6>Tesla</h6>
          <h1>Next.js</h1>
          <p>
            A strict environment that does not allow bad code to be written as
            much as possible.
          </p>
          <p>
            Get started by editing:&nbsp;
            <strong>src/pages/index.tsx</strong>
          </p>
        </div>
      </main>
    </>
  )
}
